### ISSUE TITLE
Deprecated, why?

### ISSUE THREAD

**Issue by boneyfantaseas** [dansmaculotte/nuxt-security#49]
I saw the deprecation mark, but didn't find a reason for it. Could you explain? npm support cannot be contacted that easily.
I cannot find a similar package as https://www.npmjs.com/package/nuxt-security is for Nuxt 3 only as it seems.

**Comment by rtouze** [comment]
As you can see on NPM, I don't have pushed any version for a year. I
guess it's why it has been set as deprecated.

I don't use nuxtjs nowadays and I have no time to actively support this
lib.
